name: Auto-triage to project boards

on:
  issues:
    types: [opened, labeled]
  pull_request_target:
    types: [opened, labeled]

env:
  GITHUB_TOKEN: ${{ secrets.OPENSOURCE_BOT_TOKEN }}

jobs:
  content_project:
    runs-on: ubuntu-latest
    name: Triage to Content Project
    steps:
    - name: Triages NEW issues and NEW pull requests to the Content Project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/newrelic/docs-website/projects/3'
        column_name: 'Needs Triage'

  localization_project:
    runs-on: ubuntu-latest
    name: Triage to Localization Project
    steps:
    - name: Triages NEW issues and NEW pull requests to the Localization Project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'localization') ||
        contains(github.event.pull_request.labels.*.name, 'localization')
      with:
        project: 'https://github.com/orgs/newrelic/projects/47/'
        column_name: 'Needs Triage'
